[package]
name = "rust-pkt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
af_packet = "0.2"
dns-parser = "0.7"
nom = "3.2"
num_cpus = "1.8"
pktparse = "0.2"